---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/src/e2e_test/vzconn_loadtest/server_image
    context: .
    bazel:
      target: //src/e2e_test/vzconn_loadtest:server_image.tar
  tagPolicy:
    dateTime: {}
deploy:
  kustomize:
    paths:
    - src/e2e_test/vzconn_loadtest/k8s
