---
apiVersion: v1
kind: Pod
metadata:
  name: http2-capture-pod
  namespace: pl-http2-capture
  labels:
    app: pl-test
spec:
  containers:
  - name: http2-capture-pod
    image: gcr.io/pl-dev-infra/http2-capture:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
        - SYS_ADMIN
      privileged: true
    volumeMounts:
    - name: host-tmp
      mountPath: /host/tmp
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
  volumes:
  - name: host-tmp
    hostPath:
      path: /tmp
      type: Directory
