---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http2-capture
  namespace: pl-http2-capture
  labels:
    app: pl-monitoring
spec:
  selector:
    matchLabels:
      name: http2-capture-daemonset
  template:
    metadata:
      labels:
        name: http2-capture-daemonset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: http2-capture-daemonset
        image: gcr.io/pl-dev-infra/http2-capture:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - name: host-tmp
          mountPath: /host/tmp
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
      volumes:
      - name: host-tmp
        hostPath:
          path: /tmp
          type: Directory
