---
apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/src/e2e_test/jetstream_loadtest/publisher_image
    context: .
    bazel:
      target: //src/e2e_test/jetstream_loadtest/publisher:publisher_image.tar
  - image: gcr.io/pixie-oss/pixie-dev/src/e2e_test/jetstream_loadtest/subscriber_image
    context: .
    bazel:
      target: //src/e2e_test/jetstream_loadtest/subscriber:subscriber_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - src/e2e_test/jetstream_loadtest/k8s/
